# Generated by Django 3.2.25 on 2025-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250923_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_boot_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_pole_lengths',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_ski_lengths',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
